name: trigger
on:
  pull_request:

jobs:
  a:
    uses: QuebecBashing/reusable_workflow/.github/workflows/legit.yml@4cb48c58472fa4bd4ed6afdd870e538c49618573
    # runs-on: ubuntu-latest
    # steps:
      # - uses: QuebecBashing/action@0c90c7da07791286fea7ccf3c323927fbf7fe64d # v1.0.0

