name: trigger
on:
  pull_request:

jobs:
  a:
    uses: QuebecBashing/reusable_workflow/.github/workflows/legit.yml@34f3765508e315d50d507a9869c267fe66b399ed
    # runs-on: ubuntu-latest
    # steps:
      # - uses: QuebecBashing/action@0c90c7da07791286fea7ccf3c323927fbf7fe64d # v1.0.0

